### ISSUE TITLE
`sort` not working

### ISSUE THREAD

**Issue by anhcao142** [brianloveswords/streamsql#20]
When I use table.get(), `sort` option doesn't work, other options are fine. I even turn on debug to see how the queries will be generated, and it's always missing `order by`.

the options are something like this:

```
var options = {
     page: 1,
     limit: 12,
     sort: {dateCreated: 'desc'},
     debug: true
}
```

Can you have a look at this?

**Comment by andrewhayward** [comment]
Thanks for flagging this. It's a problem with code not agreeing with docs (or tests, oddly).

**Comment by brianloveswords** [comment]
Version `0.8.1` pushed with the fix.
